// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbdinpejzjweklkbyydz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhiZGlucGVqemp3ZWtsa2J5eWR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxOTA3NDIsImV4cCI6MjA3Nzc2Njc0Mn0.fJtLPYhXxgR-4bNZlCFA-Fmze9L0UvknaH3VaQgBGdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});